site_name: TinyStacks Documentation
site_url: https://docs.tinystacks.com
theme:
  name: material
  custom_dir: overrides
  features:
    - toc.integrate
    - toc.expand
  static_templates:
    - 404.html
  palette:
      scheme: slate
      primary: black
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/tinystacks.png
  logo: assets/tinystacks.png
markdown_extensions:
- attr_list
- md_in_html
extra:
  generator: false
  homepage: https://www.tinystacks.com
  social:
    - icon: fontawesome/solid/home
      link: https://www.tinystacks.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC21VAvNozfMxrcappmJ8EBA
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Tiny_Stacks
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tinystacks
    - icon: fontawesome/brands/github
      link: https://github.com/tinystacks
    - icon: fontawesome/solid/envelope
      link: mailto:support@tinystacks.com
nav:
  - 'Introduction' : 'index.md'
  - 'Get Started':
    - 'Configure AWS and Git service connections': 'service-connections.md'
    - 'Create your first stack': 'create-stack.md'
    - 'Deploy an existing application': 'existing.md'    
  - 'How It Works':
    - 'Architecture': 'architecture.md' 
    - 'Concepts' : 'concepts.md'
    - 'How we secure your stack': 'security.md' 
    - 'Full AWS IAM Policy used by TinyStacks': 'iam-policy.md' 
  - 'Features':
    - 'Basic settings' : 'basic-settings.md'
    - 'Builds and releases': 'builds-releases.md'  
    - 'Compute': 'compute.md'
    - 'Serverless': 'serverless.md'    
    - 'Autoscaling': 'autoscaling.md'
    - 'Networking': 'networking.md'
    - 'Databases': 'database.md'
    - 'Stages': 'stages.md'
    - 'Environment variables': 'environment-variables.md'
    - 'Load balancers': 'load-balancers.md'
    - 'Domain names and HTTPS': 'domain-names-https.md'
    - 'Sidecars' : 'sidecars.md'
    - 'Logging and monitoring': 'logging-monitoring.md'
    - 'Customizing your stacks': 'customizing.md'
    - 'Data retention': 'data-retention.md'
    - 'Integrating other DevOps services' : 'integrations.md'    
    - 'Managing service connections': 'connections-manage.md'
  - 'Troubleshooting':
    - 'Troubleshooting guide': 'troubleshooting.md'  
  - 'The TinyStacks Advantage':
    - 'How TinyStacks stacks up': 'comparisons.md'

