site_name: TinyStacks Documentation
site_url: https://docs.tinystacks.com
theme:
  name: material
  features:
    - navigation.sections
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/tinystacks.png
  logo: assets/tinystacks.png
markdown_extensions:
- attr_list
- md_in_html
extra:
  generator: false
  analytics:
    provider: google
    property: UA-176124935-1
  social:
    - icon: fontawesome/solid/home
      link: https://www.tinystacks.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC21VAvNozfMxrcappmJ8EBA
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Tiny_Stacks
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tinystacks
    - icon: fontawesome/brands/github
      link: https://github.com/tinystacks
    - icon: fontawesome/solid/envelope
      link: mailto:support@tinystacks.com
nav:
  - 'Introduction' : 'index.md'
  - 'Get Started':
    - 'Create Your First Stack': 'create-stack.md'
    - 'Deploy an Existing Application': 'existing.md'    
  - 'How It Works':
    - 'Architecture': 'architecture.md' 
    - 'Concepts' : 'concepts.md'
    - 'How Do I...?': 'tinystacks-how-do-i.md'
    - 'Howe We Secure Your Stack': 'security.md'    
  - 'The TinyStacks Advantage':
    - 'How TinyStacks Stacks Up': 'comparisons.md'

