site_name: TinyStacks Documentation
site_url: https://docs.tinystacks.com
theme:
  name: material
  features:
    - navigation.sections

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

nav:
  - 'Introduction' : 'index.md'
  - 'Get Started':
    - 'Create Your First Stack': 'create-stack.md'
    - 'Deploy an Existing Application': 'existing.md'    
  - 'How It Works':
    - 'Architecture': 'architecture.md' 
    - 'Concepts' : 'concepts.md'
    - 'How Do I...?': 'tinystacks-how-do-i.md'
    - 'User Interface Guide' : 'ui-guide.md'
  - 'The TinyStacks Advantage':
    - 'How TinyStacks Stacks Up': 'comparisons.md'

