site_name: TinyStacks - Ops Console Docs
site_url: https://docs.tinystacks.com
plugins:
   - swagger-ui-tag
theme:
  name: material
  custom_dir: overrides
  features:
    - toc.integrate
    - toc.expand
  static_templates:
    - 404.html
  palette:
      scheme: slate
      primary: black
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/tinystacks.png
  logo: assets/tinystacks.png
markdown_extensions:
- attr_list
- md_in_html
extra:
  generator: false
  homepage: https://www.tinystacks.com
  social:
    - icon: fontawesome/solid/house
      link: https://www.tinystacks.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/C2YZBwGAFz
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Tiny_Stacks
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tinystacks
    - icon: fontawesome/brands/github
      link: https://github.com/tinystacks
    - icon: fontawesome/solid/envelope
      link: mailto:support@tinystacks.com
nav:
  - 'Introduction' : 'index.md'
  - 'API Reference': 'api.md'

