name: Publish Flow
on:
  push:
    branches: 
      - 'master'
      - 'push-action/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - name: Deploy mkdocs
        run: mkdocs gh-deploy --force --clean --verbose